language: rust
rust:
  - nightly

install:
  - rustup component add rust-src
  - rustup component add llvm-tools-preview
  - cd ..
  - cargo install bootimage
  - cd rt_kernel

script:
  - cargo build
