language: rust
rust:
  - nightly

before_install:
  - sudo apt update
  - sudo apt install qemu-system-x86

install:
  - rustup component add rust-src
  - rustup component add llvm-tools-preview
  - cd ..
  - cargo install bootimage

script:
  - cargo run
