language: rust
rust:
  - nightly
  
cache:
  directories:
    - $HOME/qemu

#before_script:
#  - bash -e travis-qemu.sh
#  - export PATH=$PATH:$HOME/qemu/bin

script:
  - cargo xbuild --verbose --all

install:
  - bash -e travis-qemu.sh
  - export PATH=$PATH:$HOME/qemu/bin
  - rustup component add rust-src
  - rustup component add llvm-tools-preview
  - cargo install bootimage --vers 0.8.0 --target target.json
  - cargo xbuild --verbose --all