language: rust
rust:
  - nightly

install:
  - cargo xbuild --verbose --all
  
cache:
  directories:
    - $HOME/qemu

before_script:
  - bash -e travis-qemu.sh
  - export PATH=$PATH:$HOME/qemu/bin

script:
  - cargo xbuild --verbose --all